import { ApiErrorState } from "@/components/api-error";
import { PageHeader } from "@/components/page-header";
import { Card, CardTitle, EmptyState, Meter, StatCard, Table, Td, Th } from "@/components/ui";
import { apiGet } from "@/lib/api";
import { longDate, slotLabel, truncate } from "@/lib/format";
import type { Statistics } from "@/lib/types";
import { ReportDatePicker } from "./date-picker";

// A9 · Statistics. Replaces the Summary tab — the same views Adam built with
// formulas, now generated by the backend and no longer capped by row count.
export default async function StatisticsPage({
  searchParams,
}: {
  searchParams: Promise<{ date?: string }>;
}) {
  const { date } = await searchParams;
  const result = await apiGet<Statistics>(
    `/api/admin/statistics${date ? `?date=${date}` : ""}`,
  );

  if (!result.ok) {
    return (
      <>
        <PageHeader title="Statistics" />
        <div className="p-8">
          <ApiErrorState error={result.error} status={result.status} />
        </div>
      </>
    );
  }

  const data = result.data;

  return (
    <>
      <PageHeader
        title="Statistics"
        action={<ReportDatePicker current={data.date} />}
      />

      <div className="space-y-6 p-8">
        <p className="text-[13px] text-muted">Showing {longDate(data.date)}</p>

        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <StatCard
            accent
            label="Members played"
            value={data.stats.membersPlayed}
            hint="on this date"
          />
          <StatCard label="Aced it" value={data.stats.acedIt} hint="all non-bonus correct" />
          <StatCard
            label="Answers recorded"
            value={data.stats.answersRecorded}
            hint="including bonus"
          />
          <StatCard
            label="Completion"
            value={`${data.stats.completionPct}%`}
            hint="finished all three"
          />
        </div>

        <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
          <Card>
            <CardTitle>How this date&rsquo;s questions performed</CardTitle>
            {data.questions.length === 0 ? (
              <EmptyState title="No questions were scheduled on this date" />
            ) : (
              <Table>
                <thead>
                  <tr>
                    <Th>Slot</Th>
                    <Th>Theme</Th>
                    <Th>Question</Th>
                    <Th align="right">Answered</Th>
                    <Th align="right">Correct</Th>
                  </tr>
                </thead>
                <tbody>
                  {data.questions.map((q) => (
                    <tr key={q.id}>
                      <Td className="font-semibold text-ink">{slotLabel(q.slot, q.isBonus)}</Td>
                      <Td>{q.themeLabel}</Td>
                      <Td>{truncate(q.prompt, 44)}</Td>
                      <Td align="right" className="tabular-nums">
                        {q.answered}
                      </Td>
                      <Td align="right" className="font-semibold tabular-nums text-ink">
                        {q.answered > 0 ? `${q.correctPct}%` : "—"}
                      </Td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
          </Card>

          <Card>
            <CardTitle>All time community average</CardTitle>
            {data.communityAverage.every((t) => t.answered === 0) ? (
              <p className="text-[13px] text-muted">No answers recorded yet.</p>
            ) : (
              <div className="space-y-4">
                {data.communityAverage.map((t) => (
                  <Meter key={t.key} label={t.label} pct={t.pct} value={`${t.pct}%`} />
                ))}
              </div>
            )}
            <p className="mt-5 text-[12.5px] text-muted">
              This is the number each member is compared against on her results screen.
            </p>
          </Card>
        </div>
      </div>
    </>
  );
}
